---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "hello-node"
spec:
  externalIPs: []
  healthCheckNodePort: 0
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app.kubernetes.io/component: "deployment.hello-node"
  ports:
  - name: "https"
    port: 443
    protocol: "TCP"
